### ISSUE TITLE
The extended sensor's wiring 

### ISSUE THREAD

**Issue by almostlunatic** [pvvx/ATC_MiThermometer#158]
I have several water boilers in my home (+ home of my daughter, + home of my parents). They have mechanical thermometers on them as always. I would like to control the average temperature of the water in the boilers remotely and more precisely on the room. Could I extend the sensor's 4 wires to install the sensor in (on) the boiler for seeing the water temperature on the display and on the Domoticz? And why should I - because it's already a ready device, why should one invent a new one on base of something else? Could someone give me any suggestions (maybe some photos) how could it be implemented? And, of course, I've read that adding a DS18B20 is not possible or not very simple.

More eddited: I used to use a Sonoff switch that had a DS 18B20 addded and pressed with very thin wires onto the tube of the thermostat, beside of it - it wasnot easy. Now I am getting rid of any WiFi devices for Zigbee, and additionally the POW2 does not allow attaching of additional sensors to it. That's why I want to get the temperature via the LYWSD03MMC and get everybody see on the screen if there is enaugh of warm water, and after it, I can do some automation about it.

I think I'm not alone who would achieve this.

Thanks in advance!

**Comment by pvvx** [comment]
The bus connection to the sensor is I2C. I2C is not designed for long cable connections, but for short PCB connections.

**Comment by almostlunatic** [comment]
God point! But rewriting the FW is not my cup of tea. Shure, ite would be nice to have 2 exchanging temp displays: the water boiler's on and the room's on. But I'm not capable to achieve this.

**Comment by jddonovan** [comment]
@almostlunatic  Was this a combined boiler or just a hot water one?

I've solved my heating problems without use of wires at my parent's place. I have multiple Mi-sensors that are then picked up by an Atomic Pi with a BT2MQTT bridge. This is then picked up by an ESP that controls the heating. You can choose the chosen heating area and temperature on the web interface or via Home Assistant.

The ESP it self could also pick up BT transmissions if the MQTT server or Wifi goes down. I wouldn't fully trust Home Assistant, as it tends to crash between version numbers.

The boiler is actually controlled by [EMS-ESP](https://emsesp.github.io/). The other ESP merely sends a message to this EMS-EPS to either increase or lower the temperature. The EMS-ESP creates its own wifi hotspot -> no wifi strictly required.

Personally, I would personally do it in the following way: Have one device controlling the boiler and accepting API calls over wifi, BT or ESP-NOW. Then the same device (or another, if the house is big) that collect the temperature data over the house and has the logic inside. And third, a number of these useful little sensors.

If it's JUST the hot tap water for shower and bath, I would personally just strap the BT against the boiler where the insulation is thinnest, close to the water intake valve and cover it with insulation. You can then strap a low current LED on the reset pin and use the temperature trigger to show a light if the temperature goes down too low to alert the users.

If you really want to go the I2C route, the HW versions 1.4 and 1.9(?) have the SDA SCL pins exposed, so you can solder some wires there. E.g. HW 1.8 is missing those. 15-30 cm cables might actually work, so it's not a lost cause. It just makes the sensor placing a challenge. In this case you'd need a sensor which is easy to solder pads and without LDOs etc or remove them before soldering. Reusing the one onboard might be tricky due to tiny size, but doable.

I don't have any actually useful pics, but this HA setup I made is vaguely relevant, if room heating is involved:
![image](https://user-images.githubusercontent.com/11009381/147888711-b880da46-5e9c-4b3d-91bb-15c8953058ad.png)
