### ISSUE TITLE
Cannot connect after flash firmware and setting PIN (LYWSD03MMC)

### ISSUE THREAD

**Issue by ronald8192** [pvvx/ATC_MiThermometer#174]
Device: LYWSD03MMC

After I flash the custom firmware, rename the device, and set the PIN, then it cannot connect anymore. 
During the reconnect, the Bluetooth icon did show up on the monitor.

Do I need the PIN to connect the device? I don't see the flasher webpage can enter the PIN...

Logs:
```
12:20:44 AM: Searching for devices
12:21:27 AM: Connecting to: ATC_B
12:21:36 AM: Disconnected.
12:21:36 AM: NetworkError: GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
12:21:36 AM: Reconnect 1 from 5
12:22:17 AM: Disconnected.
12:22:17 AM: NetworkError: GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
12:22:17 AM: Reconnect 2 from 5
12:22:22 AM: Disconnected.
12:22:22 AM: NetworkError: GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
12:22:22 AM: Reconnect 3 from 5
12:22:39 AM: Disconnected.
12:22:45 AM: NetworkError: GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
12:22:45 AM: Reconnect 4 from 5
12:23:00 AM: Disconnected.
12:23:00 AM: NetworkError: GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
12:23:00 AM: Reconnect 5 from 5
12:23:08 AM: NetworkError: Connection failed for unknown reason.
12:23:08 AM: Something went wrong, too many reconnects
```

P.S. I can read advertisement data from it

**Comment by pvvx** [comment]
If you entered a pin code in TelinkMiFlasher.html, then the next connection will require you to enter a pin code.

* After setting the pin code, it is often necessary to reboot the BT adapter.

**Comment by ronald8192** [comment]
I have reinstalled BT driver/reconnect the BT adapter. Still not showing up in Windows 10 new BT device scan. (only the other LYWSD03MMC with original firmware show up)

I also tried BT scan on MacBook, and Raspberry Pi using `bluetoothctl`, still cannot scan the device. The one with custom firmware but without PIN also showed up this time.


=====================
I have 3 LYWSD03MMC:
- original firmware 
- custom firmware, no PIN
- custom firmware, have PIN

**Comment by pvvx** [comment]
BLE thermometer connection and scanning is not required by system tools. The connection is made only with specialized software - [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html)

If you need the visibility of the device in the system monitor and you do not want to save the battery, then set the option: 
![image](https://user-images.githubusercontent.com/12629515/148071173-f1f29a8b-dad8-46b7-89c9-d01ad9005cea.png)

**Comment by ronald8192** [comment]
Found that the only thing need to do is reboot my computer. 
Reinstall BT driver, remove the device in device manager, reconnect BT hardware not work for me.

I also set PIN on another LYWSD03MMC today, reboot computer, the first time connect still fails (Windows did ask for PIN), second time connect succeeded.

```
5:52:48 PM: Searching for devices
5:52:56 PM: Connecting to: ATC_A
5:53:03 PM: NetworkError: Connection failed for unknown reason.
5:53:03 PM: Reconnect 1 from 5
5:53:52 PM: Disconnected.
5:55:22 PM: Searching for devices
5:55:29 PM: NetworkError: GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
5:55:29 PM: Reconnect 1 from 5
5:55:52 PM: Connecting to: ATC_A
5:55:52 PM: Detected custom Firmware
5:55:55 PM: Hardware Revision String: B1.4
5:55:55 PM: Detected custom Firmware
5:55:55 PM: Detected alternative Firmware? Use: https://pvvx.github.io/ATC_MiThermometer/TelinkOTA.html
5:55:55 PM: Hardware Version: LYWSD03MMC B1.4, Software Version: 3.5, Sensor: SHTC3
```

**Comment by Protoncek** [comment]
(after a while...)
I learned  interesting fact: 
- first i connect to xiaomi with my PC - at this point PIN is not set. Connection is succesfull.
- i set PIN code - success.
- Now i close Chrome to disconnect, reopen Chrome and try to reconnect - it won't go at all- Windows does find xiaomi and offers to enter PIN, i enter it, but connection is still UNsucsesfull.
- i grab my android phone and try the same - i can't connect either. Since i DID connect to my xiaomi without PIN before my phone has device remembered, too.
- interesting, i CAN delete my device from my phone's devices.
- now connection is succesfull when entering PIN.


So, the point is that Windows PC remembers that certain device was connected without PIN (that is, pin is 000000) and doesn't connect even if new PIN is entered. It's obviousy mandatory that this device is deleted from Win BT stack before reconnect with new PIN. 

Now, question: how do i delete known xiaomi's from Windows BT list? They are not  shown there (as is, for example my mouse, even if it's disconnected). I should have my 8 xiaomi's shown in Win BT list, but none is there...

Any clues?

**Comment by ronald8192** [comment]
Not sure which Windows version you using, but for Windows 10, should be able to see the device even if disconnected.

Control panel:
* Control Panel -> All Control Panel Items -> Devices and Printers -> Under "Unspecified"

New setting app:
* Devices -> Bluetooth and other devices -> Under "Other devices"

reboot PC might also help

**Comment by pvvx** [comment]
> 1. Remove other paired thermometer
>    
>    * I have other BT headphones paired but will not affect pairing PINed thermometer

BT headphones are not a BLE device, they are a Bluetooth device.

**Comment by scottcopus** [comment]
I had bluetooth pin pairing issues with several LYWSD03MMC devices when using Chrome on my Windows 11 laptop. Here's some things below that I found that helped me increase the reliability of my bluetooth connection and pin pairings:

1. Try to minimize your distance and obstructions as much as possible. I've seen issues even when a LYWSD03MMC device was only 2 meters away with direct line-of-sight to my laptop. 
2. If you have or had any other of these devices paired/connected to your laptop/phone/etc., try to disconnect and remove them first--even if you have connected to a different device previously. In Windows, I found my LYWSD03MMC's listed under "Other devices". FYI, when my Windows laptop still had other LYWSD03MMC's still listed and disconnected, it would have more problems connecting to other LYWSD03MMC's for some reason. 
3. Try pairing with Windows' Bluetooth settings first instead of letting Chrome/browser initiate the pin pairing process. Try to be a quick as possible when you answer the pin prompt. 
4. Once you make a successful connection from Windows, then go back to Chrome and initiate its pairing process. 
5. Unless you've replaced the battery with a higher capacity one, try not to stay directly connected via bluetooth very long. With my LYWSD03MMC's hardware version B1.5 and standard CR2032 batteries, a persistent connection will quickly drain the battery. After you're done upgrading or changing firmware settings (like from [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html)), then disconnect ASAP. If you want to take some time to examine all the available firmware settings, then export to PDF/HTML and disconnect. Reconnect later (in short time intervals) to make any changes. 
7. If you have several devices (or even one), I suggest adding the trailing bluetooth MAC address digits into the device's names, then physically labeling the devices with that MAC address, or some other unique identifying labels. 

Cheers,
Scott
