### ISSUE TITLE
Cannot apply configuration on FW 3.7

### ISSUE THREAD

**Issue by sybux** [pvvx/ATC_MiThermometer#225]
Hi there,
I've just updated 1 Xiamo ATC with your new firmware (previously running ATC1441 firmware).
When I connect with your web interface to change config, after reading configuration, I change settings I want, and when I click on send config, I can see in log "Configuration send successfuly" but just after it says disconnected.
Just to be sure problem was not one the ATC, I've flashed a second one and same behavior.

I can provide any logs or other informations, just tell me which one and how to get them :)

Thx in advance

**Comment by pvvx** [comment]
During tests, there is no shutdown when saving the configuration...
What settings are you changing?

**Comment by sybux** [comment]
just trying to remove the emotion icon. After applying configuration, I'm disconnected of the ATC after 4-5 seconds

**Comment by sybux** [comment]
any clue to try to understand why the device disconnect ?

**Comment by Protoncek** [comment]
Did you try to change the battery? Use high quality one, not cheap china crap, since they tend to “crash” at bigger power. When communicating / sending config more power is needed and i guess that module restarts because of too low battery voltage…
I recently changed battery in one module, i used cheap one and brand new shows only just over 50%…

**Comment by sybux** [comment]
Thx for reply. I've just tested with a fresh new ikea battery and it's working. previous battery was about 30%. So good point to configure use a new battery !
