### ISSUE TITLE
Change of sensor behaviour after updating to 4.5

### ISSUE THREAD

**Issue by yannpub** [pvvx/ATC_MiThermometer#405]
Here are the readings I get after update to 4.5 :
<img width="424" alt="image" src="https://github.com/pvvx/ATC_MiThermometer/assets/21988643/6deaaf0a-209b-4787-96ce-9a8584421b58">

Device is now known as "Temperature/Humidity sensor by Xiaomi " with 4.5/4.6, whereas it was considered as "BTHome sensor by Xiaomi "sensor with 4.4
My device which is still on 4.4 isn't impacted, only the 2 devices I upgraded.

**Comment by pvvx** [comment]
Since fw version 4.5, the BLE advertising protocol has been replaced from BTHome version 1 (HA_BLE) to [BTHome version 2](https://bthome.io/).

**Comment by yannpub** [comment]
I saw in the changelog, but change of protocol shouldn't change the readings of the values. Or is there an additional change to be done on the HA side to get the readings properly after the migration to the new protocol?

**Comment by cpuks** [comment]
What about removing and adding device? {Maybe extra restart of HA in-between)

**Comment by pvvx** [comment]
Nothing changes in Home Assistant with standard integrations (BTHome, Passive BLE Monitor). Switching occurs automatically...

**Comment by yannpub** [comment]
In your screenshot, sensor type is identified as 'BTHome', which was the behaviour I had with firmware 4.4, and which is providing proper reading.
After the upgrade the sensor type changes to "Temperature/Humidity sensor", which I assume is what triggers a different interpretation of the values. I am on HA 2023.11, using BTHome integration.

**Comment by pvvx** [comment]
For example, I reprogrammed a thermometer operating in the “BLE Long Range” mode from version 4.2 to 4.6.
![image](https://github.com/pvvx/ATC_MiThermometer/assets/12629515/06a2c3bd-baa0-4ab9-ba94-f89fcf9a5fdd)
Nothing has changed in the "BTHome" integration

Nothing has changed, except for temporary readings of changes in humidity that occurred from picking up the thermometer, and a temporary loss of transmission, since the thermometer switched to BLE Legacy for firmware.

**Comment by yannpub** [comment]
It seems the issue was coming from my Intel Bluetooth module, which is known to have some issues with the current 6.1 kernel : https://github.com/home-assistant/operating-system/issues/2535#issuecomment-1784219788
All my devices are now updated on FW4.6, BTHome v2 and have proper readings in HA.

Shutdown/restart of the server was the solution to get stable readings. Still doesn't understand though why the firmware update triggered this lower layer bluetooth issue and different readings, but problem solved !

**Comment by cpuks** [comment]
Cool cheers for clearing this out - I'll upgrade to 4.6 then

**Comment by yannpub** [comment]
> Cool cheers for clearing this out - I'll upgrade to 4.6 then - I knew you need to restart ;-)

Physical restart of the machine was necessary - restart of HA didn't do the trick.

**Comment by chatziko** [comment]
This is one of the strangest issues I've seen in a while. In my system I run HA OS on a VM on top of Proxmox running on a NUC. I do __not__ use the NUC's bluetooth adapter (I don't even pass it through to the VM), but I rely on two ESP32 bluetooth proxies instead.

- I first restarted the proxies, nothing changed.
- Then I restarted Home Assistant, again nothing.
- Then I rebooted the HA OS VM, still nothing!
- Finally, I rebooted the whole NUC (without much hope) and magically the problem is gone!

How is it possible to require a full host restart to solve an issue that is not even related to the host's hardware? Bluez magic...

In any case I'm super happy the issue is gone, thanks for this awesome project :smile:

**Comment by chatziko** [comment]
I declared victory too fast, the problem is still hapenning. It's much rarer now, but it's there.

Would it make sense to try v4.6, or should I better downgrade to v4.3? Anything else I could try?

![Screenshot from 2023-11-24 14-31-42](https://github.com/pvvx/ATC_MiThermometer/assets/362089/a8c9b076-9def-4dbf-9768-db827b3d0aa0)

**Comment by pvvx** [comment]
Delete all files `/var/lib/bluetooth/`

**Comment by chatziko** [comment]
For anyone having the same issue while using bluetooth proxies, I think I finally solved the issue by doing the following:
-  stop HA
- delete `/config/.storage/bluetooth.remote_scanners`
- start home assistant again

Not sure what exactly this file is doing. After the restart it was __not__ recreated right away (although it did reappear after some time) and the issue seems solved (although I was trying lots of things so I can't be 100% sure about what exactly was causing it).

**Comment by chatziko** [comment]
> @chatziko - Why is the data shown at such unequal intervals?
> Losses in reception - a lot of dropouts?

I guess the difference is that you are using Passive BLE Monitor while I am using the native BTHome integration.

In your plot it looks like you are getting __exactly__ 1 sample per minute. Based on the 60 seconds "period to use for averaging" setting, I would guess that Passive BLE Monitor creates these regular samples, independently from when exactly the raw data arrive!

In my case, on the other hand, I think the sensor reports the raw data. I set advertising interval to 6000 msecs, so under perfect conditions I suppose I should have 10 samples per minute, but many are lost so in the plots I see between 1 and 3 samples per minute.

**Comment by pvvx** [comment]
> In your plot it looks like you are getting **exactly** 1 sample per minute. 

Yes. New data arrives every 10 seconds and is rounded over a period of 60 seconds. If the data for the period is not updated, the previous value will remain.

In "BTHome Integration" the schedule is more disorderly, but there are no gaps of more than 1 minute.
