### ISSUE TITLE
(ATC_ota_40000.bin firmware) Cannot connect to ATC_xxxxx

### ISSUE THREAD

**Issue by phellarv** [pvvx/ATC_MiThermometer#422]

**Comment by phellarv** [comment]
I have now tried 2 different PC's. Same result.
![2023-11-28_15-26](https://github.com/pvvx/ATC_MiThermometer/assets/822762/a7b99974-6f1b-4929-ae27-a5cd99821b69)
And there it just hangs.

**Comment by dgoadby** [comment]
Is this your first time trying to connect with BLE or do you already have working devices?

If this is your first time then your problem might be the Bluetooth hardware. i had laptops with Bluetooth and thay didn't seem to work and I was pulling my hair out until I bought a recommended BLE dongle and, since then, all has been well. The dongle is: tp-link Bluetooth 5.0 Nano USB adaptor.

**Comment by pvvx** [comment]
Regarding the operation of the ATC_ota_40000.bin firmware, please contact https://github.com/devbis/z03mmc.

**Comment by phellarv** [comment]
I tried everything on 2 different Linux PC's, but when I booted into windows it worked right away. Painful, but if it works, it works.

**Comment by pvvx** [comment]
Linux only works with older versions of Bluetooth released before 2016.

**Comment by phellarv** [comment]
It did work with 3 out of 4 devices which I flashed today, so it is not consistent. All bought from the same vendor at the same time. And they had the same firmware before I flashed them.
But noted. I have a drive with windows on which I can boot when needed.
