### ISSUE TITLE
OTA flashing is not possible with Telink Flasher 1.9

### ISSUE THREAD

**Issue by ralf-e** [pvvx/ATC_MiThermometer#48]
In the current Telink Flasher (1.9), I am currently no longer able to flash the firmware. Does it no longer work with the current version, or am I doing something wrong here?

![grafik](https://user-images.githubusercontent.com/3521615/107874426-0615da80-6eba-11eb-9338-b62530ff1d36.png)

**Comment by PeteBa** [comment]
I had a similar issue trying to flash an "ATC firmware" device. Flashing a PVVC firmware device worked fine.

To upgrade the ATC firmware device, I ended up using the ATC flasher to get the latest pvvx firmware uploaded and then using the pvvx flasher to set the config parameters. A bit convoluted but it seemed to work.

**Comment by pvvx** [comment]
After connecting, all the necessary menus will appear and the correct firmware options will be loaded. 
Otherwise, they constantly confuse and program in LYWSD03MMC firmware from MHO-C401, etc.

**Comment by PeteBa** [comment]
That is not what I am seeing when trying to re-flash "ATC firmware" devices.

The pvvx flasher hangs after detecting ATC custom firmware. The flasher will show the "Get Config" button but not "Download Firmware". I waited for over 6 mins. I suspect that config options/format may have changed since ATC and that the detection code is in a wait loop.

See screenshot below:


![image](https://user-images.githubusercontent.com/16738570/107954000-d20ee800-6f93-11eb-8fac-8a5d5b05853a.png)

**Comment by pvvx** [comment]
![image](https://user-images.githubusercontent.com/12629515/107956930-f2996b00-6fb0-11eb-9a73-f3f591d1730a.png)

**Comment by PeteBa** [comment]
Thanks, yes, the issue is when trying to re-flash older ATC firmware with your newer firmware.

As a suggestion, when your flasher detects an unrecognised firmware then it could just show the "download firmware" section but hide the "configure options" items. This would allow the user to upgrade toy your version from an older/unsupported firmware

**Comment by pvvx** [comment]
> As a suggestion, when your flasher detects an unrecognised firmware then it could just show the "download firmware" section but hide the "configure options" items. This would allow the user to upgrade toy your version from an older/unsupported firmware

Then many will be flashed into the firmware for another device and there will be many repetitive questions - "does not work ..."

**Comment by PeteBa** [comment]
It is a good question and I can see the issue. I notice that the devices look physically different and you may be able to use that. Could you introduce a selection dialog to guide the user in choosing the right firmware ? This would only be needed when the firmware cannot be recognised. Perhaps something like below:

![image](https://user-images.githubusercontent.com/16738570/107975854-9f271d00-6fb0-11eb-934e-da37f0f7e8b8.png)

@ralf-e , I hope I didn't hijack your issue and that this is similar to your circumstances ?

**Comment by ralf-e** [comment]
I have now tested the flasher version 1.9 again with some of my sensors.

Telink Flasher for Mi Thermostat 1.9 only offers me a file selection / firmware update if a pvvx-ATC version is already flashed on the respective sensor (MHO or LYWSD) (version 2.0).

This selection is not available for sensors with older ATC versions and also for sensors with original firmware, i.e. a firmware update or flashing of new sensors does not work!

**Comment by ralf-e** [comment]
OK, for the sensors with org. Firmware I found my errors now:
Before the update, the sensor must be activated ... (easy to read over) ...

**Comment by pvvx** [comment]
This translates into a separate project. I'm not an HTML designer :)
What I can, I will build in ...

**Comment by pvvx** [comment]
https://pvvx.github.io/ATC_MiThermometer/TelinkOTA.html
